# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: diwalaku <diwalaku@codam.student.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2025/01/14 19:47:04 by diwalaku      #+#    #+#                  #
#    Updated: 2025/01/14 19:59:57 by diwalaku      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

NAME		= megaphone

# Configuration
CC			= c++
CPP_FLAGS	= -Wall -Werror -Wextra
CPP_FLAGS	+= -std=c++98

# Source Files
SRC			= megaphone.CPP_FLAGS

# Object Files and Directories
OBJDIR		= obj
OBJ			= $(addprefix $(OBJDIR)/, $(notdir $(SRC:.c=.o)))

# Objectives
all:	$(NAME)

$(NAME):